import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppFunProvider } from "@/context/AppFun";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "flower of life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppFunProvider>
          {children}
        </AppFunProvider>
      </body>
    </html>
  );
}
