import { Inter } from "next/font/google";
import { AppFunProvider } from "@/context/AppFun";

// استدعاء خط Inter من Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "flower of life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AppFunProvider>
          {children}
        </AppFunProvider>
      </body>
    </html>
  );
}
